name: Alerta no Discord

on:
  push:    # dispara sempre que fizer commit ou merge
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        uses: sarisia/actions-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "GitHub Actions"
          content: |
            ğŸš¨ **Novo Commit no RepositÃ³rio**
            ğŸ“¦ RepositÃ³rio: ${{ github.repository }}
            ğŸ‘¤ Autor: ${{ github.actor }}
            ğŸ“ Mensagem: ${{ github.event.head_commit.message }}
            ğŸ”— Link: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
